---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/cash?useSSL=false
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy

---

spring:
  profiles: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password: sa