---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/cash?useSSL=false
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy